package Main_Views;

import Class.Usuario;
import DAO.UsuarioDAO;

import java.util.Date;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

public class View_Cadastro extends javax.swing.JFrame {

    public View_Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        IconCadastro = new javax.swing.JLabel();
        BackgroundConteudo = new javax.swing.JPanel();
        TitleCadastro = new javax.swing.JLabel();
        TitleNome = new javax.swing.JLabel();
        TitleCelular = new javax.swing.JLabel();
        TitleEmail = new javax.swing.JLabel();
        TitleSenha = new javax.swing.JLabel();
        TitleSenhaNovamente = new javax.swing.JLabel();
        jTextNomeUser = new javax.swing.JTextField();
        jTextCelular = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jPasswordSenha = new javax.swing.JPasswordField();
        jPassowordSenhaNovamente = new javax.swing.JPasswordField();
        jButtonFazerLogin = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(58, 56, 77));

        IconCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-user_128.png"))); // NOI18N

        BackgroundConteudo.setBackground(new java.awt.Color(38, 40, 55));

        TitleCadastro.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        TitleCadastro.setForeground(new java.awt.Color(255, 255, 255));
        TitleCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleCadastro.setText("cadastro");
        TitleCadastro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        TitleCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TitleNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleNome.setForeground(new java.awt.Color(255, 255, 255));
        TitleNome.setText("Nome de Usuario *");

        TitleCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleCelular.setForeground(new java.awt.Color(255, 255, 255));
        TitleCelular.setText("Celular(Com DDD)");

        TitleEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleEmail.setForeground(new java.awt.Color(255, 255, 255));
        TitleEmail.setText("Email");

        TitleSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleSenha.setForeground(new java.awt.Color(255, 255, 255));
        TitleSenha.setText("Senha *");

        TitleSenhaNovamente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleSenhaNovamente.setForeground(new java.awt.Color(255, 255, 255));
        TitleSenhaNovamente.setText("Senha Novamente *");

        jButtonFazerLogin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButtonFazerLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFazerLogin.setText("Fazer Login");
        jButtonFazerLogin.setBorderPainted(false);
        jButtonFazerLogin.setContentAreaFilled(false);
        jButtonFazerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFazerLoginActionPerformed(evt);
            }
        });

        jButtonCadastro.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButtonCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastro.setText("Cadastrar-se");
        jButtonCadastro.setBorderPainted(false);
        jButtonCadastro.setContentAreaFilled(false);
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundConteudoLayout = new javax.swing.GroupLayout(BackgroundConteudo);
        BackgroundConteudo.setLayout(BackgroundConteudoLayout);
        BackgroundConteudoLayout.setHorizontalGroup(
            BackgroundConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TitleCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNomeUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TitleCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TitleEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TitleSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TitleSenhaNovamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundConteudoLayout.createSequentialGroup()
                        .addComponent(jButtonFazerLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jButtonCadastro))
                    .addComponent(jPassowordSenhaNovamente)
                    .addComponent(jPasswordSenha))
                .addContainerGap())
        );
        BackgroundConteudoLayout.setVerticalGroup(
            BackgroundConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundConteudoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(TitleCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(TitleEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(TitleSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TitleSenhaNovamente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassowordSenhaNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFazerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(BackgroundConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(IconCadastro)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(IconCadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
   
    String nome = jTextNomeUser.getText();
    String email = jTextEmail.getText();
    String senha = new String(jPasswordSenha.getPassword());
    String senhaNovamente = new String(jPassowordSenhaNovamente.getPassword());
    String celular = jTextCelular.getText();

    if (nome.isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo nome deve ser preenchido!");
        return;
    }

    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo email deve ser preenchido!");
        return;
    }

    if (senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo senha deve ser preenchido!");
        return;
    }

    if (senhaNovamente.isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo senha novamente deve ser preenchido!");
        return;
    }

    if (!email.contains("@")) {
        JOptionPane.showMessageDialog(this, "O email deve conter um '@'!");
        return;
    }

    if (!celular.isEmpty() && celular.length() != 11) {
        JOptionPane.showMessageDialog(this, "O celular deve ter 11 números!");
        return;
    }

    if (!senha.equals(senhaNovamente)) {
        JOptionPane.showMessageDialog(this, "As senhas não são iguais!");
        return;
    }
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    if (usuarioDAO.emailExiste(email)) {
        JOptionPane.showMessageDialog(this, "O email informado já está em uso. Por favor, escolha outro email.");
        return;
    }

    Usuario usuario = new Usuario();
    usuario.setNomeDeUsuario(nome);
    usuario.setEmail(email);
    usuario.setSenha(senha);
    
        
    if (!celular.isEmpty()) {
        usuario.setCelular(celular);
    }
    Date dataCriacao = new Date();
    Timestamp timestamp = new Timestamp(dataCriacao.getTime());
    System.out.println("Timestamp: " + timestamp);
    usuario.setData_Criacao_User(timestamp);

    usuarioDAO.cadastroUsuario(usuario);

    JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");

    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonFazerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFazerLoginActionPerformed
    View_Login ViewLogin = new View_Login();
        ViewLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFazerLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BackgroundConteudo;
    private javax.swing.JLabel IconCadastro;
    private javax.swing.JLabel TitleCadastro;
    private javax.swing.JLabel TitleCelular;
    private javax.swing.JLabel TitleEmail;
    private javax.swing.JLabel TitleNome;
    private javax.swing.JLabel TitleSenha;
    private javax.swing.JLabel TitleSenhaNovamente;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonFazerLogin;
    private javax.swing.JPasswordField jPassowordSenhaNovamente;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JTextField jTextCelular;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNomeUser;
    // End of variables declaration//GEN-END:variables
}
